# Generated by Django 4.2.3 on 2023-09-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_products',
            field=models.ManyToManyField(related_name='added_to_carts_by', to='mainpage.product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(related_name='favorited_by', to='mainpage.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
