# Generated by Django 4.2.3 on 2023-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
