# Generated by Django 4.2.3 on 2023-10-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_productcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
